<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Zebo.Commerce</PackageId>
    <Version>0.1.0</Version>
    <Authors>Zebo Engineering</Authors>
    <Company>Zebo</Company>
    <Description>Lightweight .NET SDK for the Zebo Commerce API</Description>
    <RepositoryUrl>https://github.com/zebodotdev/commerce</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
