version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/sdks/dotnet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/sdks/dotnet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
