<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Inttegro</PackageId>
    <Version>1.0.0</Version>
    <Authors>Inttegro Engineering</Authors>
    <Company>Inttegro</Company>
    <Description>Official .NET SDK for the Inttegro API</Description>
    <RepositoryUrl>https://github.com/zebodotdev/inttegro-sdk-dotnet</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
